### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by Crell** [r-daneelolivaw/mastodon-api-php#10]
It seems this project is largely abandoned.  It's one of the few such libraries that seems to actually work, though. :smile: 

Is it possible to have a tagged release so that composer doesn't force us to use "minimum stability: dev" in order to use it?  Even if it's not a 1.0, any tagged number would be helpful.

**Comment by colorfield** [comment]
Sorry for the super late reply, obviously missed that one. Here is the initial release https://github.com/colorfield/mastodon-api-php/releases/tag/v0.1.0

It's very outdated though, still using php 5.6, so going to bump to >=8.1 and use a recent version of Guzzle in a next release.

**Comment by colorfield** [comment]
The release with php 8.1, guzzle ^7.7.0 https://github.com/colorfield/mastodon-api-php/releases/tag/0.1.1 (makes it usable with e.g. Drupal 10)
